### ISSUE TITLE
Exporting surfaces doesn't work in Blender 4.2.3 in windows

### ISSUE THREAD

**Issue by Lourencosm** [tkeskita/swiftBlock#15]
I get an error while exporting, if my case also exports surfaces (when using projections):

`Python: Traceback (most recent call last):
File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\swiftBlock\__init__.py", line 642, in execute
    mesh, cells = writeMesh(ob, self.filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\swiftBlock\utils.py", line 485, in writeMesh
    geos = writeProjectionObjects(ob, mesh.geomPath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\swiftBlock\utils.py", line 646, in writeProjectionObjects
    bpy.ops.export_mesh.stl(filepath = path + '/{}.stl'.format(o), use_selection=True)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.export_mesh.stl" error, could not be found
`

**Comment by Lourencosm** [comment]
Works fine in Blender 4.1 in windows

**Comment by Lourencosm** [comment]
Check this issue on stackexchange:
[https://blender.stackexchange.com/questions/322693/how-to-export-combinations-of-models-as-stl](url)

Solution:
in file 'utils.py' replace line 646:
`bpy.ops.export_mesh.stl(filepath = path + '/{}.stl'.format(o), use_selection=True)`
with:
`bpy.ops.wm.stl_export(filepath = path + '/{}.stl'.format(o), export_selected_objects=True)`
